#define GOLDFISH_IMAGE "res/GadgetGoldFish.bmp"
#define PIRANHA_IMAGE "res/GadgetPiranha.bmp"
#define SNOWBALL_IMAGE "res/GadgetSnowball.bmp"
#define SWITCH_IMAGE "res/GadgetSwitch.bmp"
#define EXTRALIFE_IMAGE "res/GadgetExtraLife.bmp"
#define SNOWBOOTS_IMAGE "res/GadgetSnowboots.bmp"
#define ROTTENFISH_IMAGE "res/GadgetRottenFish.bmp"
